INSERT INTO `CONVERSION` (CON_FROMTO, CON_RATE)
VALUES ('SEKSEK', 1),
       ('SEKUSD', 0.11 ),
       ('SEKGBP', 0.087),
       ('SEKCNY', 0.76),
       ('USDUSD', 1),
       ('USDSEK', 8.98),
       ('USDGBP', 0.78),
       ('USDCNY', 6.86),
       ('GBPGBP', 1),
       ('GBPSEK', 11.45),
       ('GBPUSD', 1.28),
       ('GBPCNY', 8.74),
       ('CNYCNY', 1),
       ('CNYSEK', 1.31),
       ('CNYUSD', 0.15),
       ('CNYGBP', 0.11);